# Generated by Django 4.0.4 on 2022-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(default='Brasil', max_length=30)),
                ('coordinates', models.CharField(max_length=30, null=True)),
                ('complement', models.CharField(max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
