# Generated by Django 4.0.4 on 2022-06-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='addresses',
        ),
    ]
