# Generated by Django 4.0.4 on 2022-07-14 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_customer_email_customer_nickname_customer_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 7, 14)),
        ),
    ]
