# Generated by Django 4.0.4 on 2022-04-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.category')),
            ],
        ),
    ]
