# Generated by Django 4.0.4 on 2022-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='categories',
            field=models.ManyToManyField(to='appliances.category'),
        ),
    ]
