# Generated by Django 4.0.4 on 2022-04-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appliances", "0005_symptom_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=150)),
            ],
        ),
    ]
