# Generated by Django 4.0.4 on 2022-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0006_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='causes',
            field=models.ManyToManyField(to='appliances.problem'),
        ),
    ]
