# Generated by Django 4.0.4 on 2022-04-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solutions',
            field=models.ManyToManyField(to='appliances.solution'),
        ),
    ]
