# Generated by Django 4.0.4 on 2022-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0009_problem_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solutions',
            field=models.ManyToManyField(blank=True, to='appliances.solution'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='categories',
            field=models.ManyToManyField(blank=True, to='appliances.category'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='causes',
            field=models.ManyToManyField(blank=True, to='appliances.problem'),
        ),
    ]
