# Generated by Django 4.0.4 on 2022-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0011_historic_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='appliances.symptom'),
        ),
    ]
