# Generated by Django 4.0.4 on 2022-04-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0012_historic_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='problems',
            field=models.ManyToManyField(blank=True, to='appliances.problem'),
        ),
    ]
