# Generated by Django 4.0.4 on 2022-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0013_historic_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='solutions',
            field=models.ManyToManyField(blank=True, to='appliances.solution'),
        ),
    ]
