# Generated by Django 4.0.4 on 2022-04-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0014_historic_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance'),
        ),
    ]
