# Generated by Django 4.0.4 on 2022-06-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_customer_address'),
        ('appliances', '0015_historic_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.organization'),
        ),
    ]
