# Generated by Django 4.0.4 on 2022-04-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0015_historic_appliance'),
        ('profiles', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.historic')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.organization')),
            ],
        ),
    ]
