# Generated by Django 4.0.4 on 2022-06-24 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0016_historic_org'),
        ('profiles', '0005_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.historic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.organization')),
            ],
        ),
    ]
