# Generated by Django 4.0.4 on 2022-06-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 6, 26)),
            preserve_default=False,
        ),
    ]
