# Generated by Django 4.0.4 on 2022-06-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
