# Generated by Django 4.0.4 on 2022-07-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_status_alter_service_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.status'),
        ),
    ]
