# Generated by Django 4.0.4 on 2022-08-01 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
    ]
